### ISSUE TITLE
About train_semi.py

### ISSUE THREAD

**Issue by yjcreation** [luogen1996/OneTeacher#4]
When i excute the script, it met the problem(it appeared epoch 12):
`Traceback (most recent call last):
  File "train_20.py", line 920, in <module>
    main(opt)
  File "train_20.py", line 818, in main
    train(opt.hyp, opt, device, callbacks)
  File "train_20.py", line 511, in train
    out, train_out,pseudo_class_one_hot =model_teacher(unlabel_imgs_weak_aug,augment=True)
  File "/home/yy/miniconda3/envs/general/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yy/log/4.semi-supervised/OneTeacher-main/models/yolo.py", line 523, in forward
    return self.forward_augment(x)  # augmented inference, None
  File "/home/yy/log/4.semi-supervised/OneTeacher-main/models/yolo.py", line 533, in forward_augment
    xi = scale_img(x.flip(fi) if fi else x, si, gs=int(self.stride.max()))
  File "/home/yy/log/4.semi-supervised/OneTeacher-main/utils/torch_utils.py", line 300, in scale_img
    s = (int(h * ratio), int(w * ratio))  # new size
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'`@ @luogen1996

**Comment by iu110** [comment]
请问你有解决这个问题吗

**Comment by July-1024** [comment]
> 请问你有解决这个问题吗

请问你解决了吗？遇到了一样的问题
