### ISSUE TITLE
do you know how to solve this issue  "NameError: name '_SPLITS_COCO5_FORMAT' is not defined" ? 

### ISSUE THREAD

**Issue by Yaroto02303** [luogen1996/OneTeacher#7]
when i execution this command ,

"python data_processing/generate_random_supervised_seed_yolo.py  --dataset_name 'coco_2017_train' --random_seeds 0,1,2,3,4,5,6,7,8,9 --random_file  ./data_processing/COCO_supervision.txt --random_percent 10.0 --output_file ./dataseed/COCO_supervision_10.json"

this error was occured .

"Traceback (most recent call last):
  File "data_processing/generate_random_supervised_seed_yolo.py", line 7, in <module>
    from builtin import *
  File "/home/ssod/OneTeacher/data_processing/builtin.py", line 175, in <module>
    register_coco5(_root)
  File "/home/ssod/OneTeacher/data_processing/builtin.py", line 115, in register_coco5
    for _, splits_per_dataset in _SPLITS_COCO5_FORMAT.items():
NameError: name '_SPLITS_COCO5_FORMAT' is not defined"

please help me.

**Comment by xinzhichao** [comment]
I meet the same error, have you resolve it?

**Comment by xinzhichao** [comment]
I meet the same error, have you resolve it? @Yaroto02303

**Comment by thunder95** [comment]
same problem
